name: hpylori
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - r-base=4.1.3
  - r-testthat
  - r-pkgload
  - r-gunifrac
  - r-picante
  - r-randomforest
  - r-devtools
  - r-readxl
  - r-sjPlot
  - r-questionr
  - r-biocmanager
  - r-tidyverse
  - r-kableExtra
  - r-magrittr
  - r-ggpubr
  - r-rcolorbrewer
  - r-tidytree
  - r-withr
  - r-rmarkdown
  - bioconductor-phyloseq
  - bioconductor-deseq2
  - bioconductor-complexheatmap
  - bioconductor-microbiome
